name: "On Push Workflows"

on:
  push:
    paths:
      - 'app/test/**'
      - 'app/other/**'
      - 'hello.txt'

jobs:
  act-on-push-job:
    timeout-minutes: 5
    name: 'act on push'
    runs-on: ubuntu-latest
    steps:
      - name: 'hello variables'
        run: |
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_REF: ${GITHUB_REF}"
